linters:
  enable-all: true
  disable:
   - scopelint
   - paralleltest
   - noctx
   - godox
   - wsl
   - lll
   - forbidigo
   - nlreturn
   - gomnd
  fast: true

run:
  skip-dirs:
    - build
    - artifacts

linters-settings:
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: camel
        yaml: kebab
        xml: camel
        bson: camel
        avro: snake
        mapstructure: kebab

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - gochecknoglobals
        - testpackage
    - path: cmd/git-sv/main.go
      linters:
        - gochecknoglobals
        - funlen