version: "1.0"

versioning:
    update-major: []
    update-minor:
        - feat
    update-patch:
        - build
        - ci
        - chore
        - fix
        - perf
        - refactor
        - test

tag:
    pattern: 'v%d.%d.%d'

commit-message:
    footer:
        issue:
            key: issue
            add-value-prefix: '#'
    issue:
        regex: '#?[0-9]+'
